### ISSUE TITLE
Check how Grafana alerts can be used

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-documentation#104]
**As a Q&A / support / development team member** I would like to be alerted when some conditions are met.

## Acceptance criteria

- An alert is raised if the error / session ratio is > 2%.
- The alert is sent by email, Slack and Discord.

## Tasks

- [x] Write a panel that is able to display the error / session ration as a percentage.
- [ ] Trigger an alert over 2%.

**Comment by amtins** [comment]
@defagos looks like a letter is missing in Grafana or am I dreaming?

**Comment by defagos** [comment]
I created a dashboard folder in which I am working on dashboards. One of them is a time series which displays the error percentage over time. Should be compatible with alerts.

**Comment by defagos** [comment]
I see only two ways of configuring alerts:

 - SNS (but this is a task to be discussed with @jboix).
 - Slack (but I am no admin).

I'll therefore return this task to the backlog for the moment.

**Comment by jboix** [comment]
I've created an issue to setup the SNS topic and email notification : SRGSSR/pillarbox-monitoring-infra/issues/8
