### ISSUE TITLE
Discuss Google Cast and custom data source integration

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-documentation#14]
**As a Pillarbox team** we need to grow a common understanding of the various challenges of integrating Google Cast directly in the Pillarbox product, knowing that arbitrary data sources / analytics will be supported.

# Acceptance criteria

- Discuss Google Cast integration at a high level in mobile and web players.
- Discuss what this could mean for the Google Cast receiver implementation.
- Write down any information that could be helpful (knowing that we probably have still a lot to learn).

# Tasks

- [ ] Discuss.
- [ ] Document.

**Comment by amtins** [comment]
# Pillabox Google Cast Receiver

## Abstract

Reflection of having a Google Cast Receiver extensible and customizable by integrators.

## Preliminary work

- Determine if **video.js**, then **Pillarbox Web** can be used as a player for the receiver
  - What does this mean for the [standard visual components](https://developers.google.com/cast/docs/styled_receiver) provided by Google?
- Determine what extensibility and customization of the receiver means for the integrator
  - What does it mean for the standard Google defined [Customize UI](https://developers.google.com/cast/docs/web_receiver/customize_ui) if Pillarbox Web is used?
- Determining a standard format for data describing media
  - Google's standard for [MediaData](https://developers.google.com/cast/docs/media/messages#MediaData)
  - Google's standard for supported [Media](https://developers.google.com/cast/docs/media)
  - Google's standard for the type of HLS [audio](https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.messages#.HlsSegmentFormat) and [video](https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.messages#.HlsVideoSegmentFormat) fragments
- Determine the feasibility of connecting to any data source
- Determine the complexity and feasibility of queues management and the implications for Pillarbox Web
  - Google's standard for [queues](https://developers.google.com/cast/docs/web_receiver/queueing) management. See [LoadRequestData queueData](https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.messages.LoadRequestData#queueData), [QueueData](https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.messages.QueueData) and [QueueItem](https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.messages.QueueItem), 
  - _Google's standard for [media browse](https://developers.google.com/cast/docs/web_receiver/media-browse)_
