### ISSUE TITLE
Validate analytics with the GD

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-documentation#27]
**As a GD analyst** I want to be sure that analytics standards are implemented according to the specifications by all SRG SSR apps depending on Pillarbox.

# Acceptance criteria

- The Pillarbox demo has been validated by GD analysts.

# Tasks

- [x] Ensure that page views, events and streaming analytics can be tested in the Pillarbox demo.
- [x] Submit the demo to GD analytics.

**Comment by defagos** [comment]
Request for validation sent.

**Comment by GoetzMar** [comment]
Hi @defagos 
Maybe you have seen the e-mail that I've send to TagCommander and Mapp. At first glance it seems to me that Pillarbox is sending the requests when they should be send and they looked correct. I guess the problems I've found are on TagCommander or Mapp side. 

I tested Android so far. Will have to double check some things and of course also test iOS. Will get back to you with further feedback.

**Comment by defagos** [comment]
Thank you very much for the update and your tests so far.

**Comment by GoetzMar** [comment]
Hi @defagos 
As expected the problem I mentionened in my comment before was related to TagCommander. It is fixed now and I tested the Android implementation successfully for Mapp Intelligence.

Do you know how Comscore was tested when it got implemented? I asked Mediapulse and the Comscore consultant by e-mail and didn't get a reply yet. Maybe you or one of your colleagues has an idea.

iOS is not tested yet. How much time pressure is there for the testing? I'm around next week and than off for two weeks. Not sure if I can do the testing next week.

**Comment by defagos** [comment]
Hi @GoetzMar,

Thank you very much for the update.

Regarding the comScore implementation we went through Kantar as usual. They follow their own validation procedure, likely a mixture of use cases and manual event inspection.

For the Apple implementation there is no emergency. It can wait until you are back (we might deliver a demon update in the meantime).

Thank you very much for your help.

**Comment by GoetzMar** [comment]
Alright. I'll ask the Kantar/Comscore people who needs access to a test environment and will provide you the e-mail adresses. 

Thanks, good to know that we are not in a hurry.

**Comment by GoetzMar** [comment]
Hi @defagos 
Can you please invite srg.adi.da@gmail.com for iOS and Android testing since we have a new account to do the testings? Thx.

**Comment by defagos** [comment]
Hi @GoetzMar. An invitation has been sent.

Best.

**Comment by GoetzMar** [comment]
Hey @defagos 
Unfortunately I didn't get an e-mail nor can I see the app in Testflight.

**Comment by defagos** [comment]
Sorry, my mistake. You already accepted the invitation but had no access to the Pillarbox demo apps themselves. This should be fixed now.

**Comment by defagos** [comment]
Nope, the TV app is the same (same application identifier) but must be deployed to an Apple TV device with TestFlight for tvOS. Just use the same account with TestFlight on tvOS and you should be good to go.

**Comment by GoetzMar** [comment]
We don't have such a device, so therefor can't test it. How do you do it usually? Is there a way to simulate it or do you actually use a real device?

**Comment by defagos** [comment]
You can build the project yourself on a Mac of course, but using a real device is simpler. But there is no difference between the iOS and tvOS code, so if results are correct on iOS they should be correct on tvOS.

**Comment by GoetzMar** [comment]
Hi @defagos 
Checked the iOS version. Mostly looking good. But no "seek" events seem to be send. Tried it with several of the available videos (vod/live). All the other events worked, namely:
- play
- pause
- eof
- uptime
- pos
- stop

Can you please investigate where the problem could be? As always, feel free to invite me for a call if needed.

**Comment by defagos** [comment]
This is actually expected.

On iOS we have implemented [trick mode](https://github.com/SRGSSR/pillarbox-apple/pull/466) , a way to improve the seek user experience during continuous interactions (e.g. slider being dragged). Trick mode requires the player to be paused when the user interaction with begins, and to be resumed when the user interaction ends (if the user was playing before, of course). This ensures the player can cope as fast as possible with seek requests.

This explains why you don't see any `seek` if you are using the slider, which I assume you do. But if you use a discrete seek method, like one of the skip buttons available, you'll see that in this case the player is not paused and that you obtain a `seek` event.

In any case, the `pause` or `seek` event occuring before the seek must have the correct timestamp, and similarly the `play` after, so the total playback duration must be unaffected. In fact, if you look at what comScore is doing, their SDK has no concept of `seek` event. Pause is used to mark both pauses as well as the start of seek operations.

Hope this answers your question.

Best regards and thanks for your tests.

**Comment by GoetzMar** [comment]
Thanks for the explanation. That's great news. Meaning the testing was successful. Just did a quick test for the seek function in the way you described. You were right that I used the slide before. Now I used the discrete seek method and I see the events.

Just to be sure. There is no option to test "Event" in this environment. For the play apps I used the program guide, since this is one of the few events available. If there is no events, we can close this task. If I missed it, please let me know where to find it and I'll check it.

**Comment by defagos** [comment]
You are right, we did not implement any event test in the Pillarbox demo. The reason is that we are using the exact same code under the hood to send streaming events, so testing streaming means testing events at the same time.

**Comment by GoetzMar** [comment]
Perfect. Thanks a lot. So let's close this task.
