### ISSUE TITLE
Align `uptime` behavior with Android and the web

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-documentation#39]
**As a Pillarbox team member** I want the same rules to be applied for `uptime` intervals.

# Acceptance criteria

- Apple and Android implementations have been aligned.
- No conflict arises with [Mapp documentation](https://documentation.mapp.com/1.0/en/current-position-of-the-multimedia-file-pos-19104855.html) for this event.

# Tasks

- [x] Decide what we should do.
- [x] Implement the decision (create dedicated issues if appropriate).

**Comment by defagos** [comment]
Next step: Ask for @pyby opinion first, then ask the GD.

**Comment by defagos** [comment]
Note that `uptime` is currently only sent **in live conditions**, as noted by @pyby. So this event might still have a purpose, namely measuring the consumption in live conditions.

**Comment by defagos** [comment]
According to the [implementation concept](https://confluence.srg.beecollaboration.com/display/INTFORSCHUNG/Implementation+Concept):

> UPTIME | Mandatory only in Live Streaming media views (not VOD/AOD) objects. Uptime events should be sent every 60 seconds, with a time shift delay of 30 seconds from the initial play of the streaming.

**Comment by defagos** [comment]
An issue has been [created](https://github.com/SRGSSR/pillarbox-apple/issues/470) for the Apple implementation.

**Comment by defagos** [comment]
The 3 implementations should be aligned for intervals but we still have to check whether we are (more or less) aligned about sending _near the live edge_.

**Comment by defagos** [comment]
Letterbox web was not implementing the live edge criterium (since day one). This will be fixed and implemented in Pillarbox web as well.

**Comment by amtins** [comment]
I took the time to create an [issue](https://github.com/SRGSSR/srgletterbox-web/issues/843) as well as to reread the official specification very carefully. It appears that the specification contradicts itself, so depending on which definition you use, you have a 50% chance of making a mistake.

Please refer to the `scenario` in **Story 4 (Seeking a livestream)** of the documentation [standard streaming events: sequence of events for media player actions](https://confluence.srg.beecollaboration.com/pages/viewpage.action?pageId=19727460)

Finally, after reading a new specification, even if it's older than the standard specification to be used for players, it mentions [`tracking the event UPTIME should not be sent anymore`](https://confluence.srg.beecollaboration.com/display/INTFORSCHUNG/Implementation+Concept+-+draft#ImplementationConceptdraft-6.4.2.5ReviewofMediaActionUPTIME) so it's **SHOULD** and not a **MUST**, what should we conclude from this?

**Comment by defagos** [comment]
We received an answer from the GD that we should likely always send `uptime`, not only in live conditions.

**Comment by defagos** [comment]
Tasks created for [Android](https://github.com/SRGSSR/pillarbox-android/issues/204) and [Apple](https://github.com/SRGSSR/pillarbox-apple/issues/523).
