### ISSUE TITLE
Discuss track management API

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-documentation#44]
**As a team** we need to have a common understanding of what our API should provide and what it should not.

# Acceptance criteria

- The track management API has been discussed and decisions have been documented.

# Tasks

- [x] Discuss.

**Comment by defagos** [comment]
As discussed with @amtins and @StaehliJ, the Pillarbox player API will not provide clever behaviors like what [SRG Media Player](https://github.com/SRGSSR/srgmediaplayer-apple) currently does on Apple platforms. For example we won't implement a mode where switching the audio track chooses the best possible language for subtitles, based on device or application language. If this is later needed this behavior can be provided with higher-level APIs, but the low-level API should be simple.

There will be only two exceptions to this rule:

- Forced subtitles should be hidden from view and transparently associated with content based on audio language selection:
    - The player API for subtitles will not return forced subtitles.
    - Forced subtitles cannot be set directly.
    - When clearing subtitles the player will automatically enable forced subtitles for the current audio language, if any.
- AD and SDH system preferences will be implemented by the player where applicable.

**Comment by amtins** [comment]
@defagos echoing the discussion we had yesterday and the fact that I'm no longer sure how strictly to apply the specification, we can keep it as it is, https://github.com/SRGSSR/pillarbox-documentation/issues/44#issuecomment-1663827441. 

If a question is raised by the packaging team or an integrator, we could ask the specification authors to clarify these properties and their strict interpretation as well as the examples provided in the specification.

As a reference, an answer I gave on a similar subject https://github.com/SRGSSR/srgletterbox-web/issues/769#issuecomment-1482557458
