### ISSUE TITLE
Discuss SAM media playback context delivery requirements and possible simplifications

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-documentation#85]
**As a Pillarbox development team** we would like to help the backend team design media playback context delivery services (currently _media composition_) that are simpler, lighter and appropriate for our use cases.

# Acceptance criteria

- Discuss minimal requirements.
- Identify possible simplifications.

# Hints

Some topics:

- Overlapping segments.
- Chapters / chapters only.
- Naming (e.g. chapters).
- Resources.
- Client requirements (e.g. to let the server return the best resource).
- Highlights.
- Radio programs.
- Periodic updates.
- SwissTXT-related stuff.
- ...

# Tasks

- [x] Discuss within the team and write down everything that can be useful.

**Comment by defagos** [comment]
Pillarbox does not need all the information that Letterbox was using. A recommended minimum would be:

- Resource to be played:
    - URL.
    - MIME type.
    - Stream type (live, DVR, on-demand).
    - Container information (audio / video).
    - If an Akamai token is required.
    - DRM flavors / license and certificate URLs.

**Comment by defagos** [comment]
@SRF-Dennis FYI we discussed minimal needs within the team ahead of our meeting next week. You might want to forward our output with your team. Thanks!

**Comment by SRF-Dennis** [comment]
@defagos Information was forwarded to the team. Thank you!

**Comment by defagos** [comment]
## Design meeting, October 16th

- Formats for successful retrieval/failure. Common metadata with resource only provided in case of success.
- Server should tailor the response based on information transmitted by the client (e.g. language, platform).
- Additional playback context (e.g. use of a token, license or certificate URL) in custom data.
- Blocking reasons can be delivered more generically as errors, with optionally attached metadata (but no source).

## Design meeting, October 30th

- Video/audio fragments required by the web player if the URL has no extension. On Apple platforms extension is required, otherwise the player might not be able to play the content.
- For sprite sheets creating a standard is trickier since there is no formal standard (can be provided as metadata or in master playlists with non-standard tags). Here are the Bitmovin [specification](https://developer.bitmovin.com/playback/docs/webvtt-based-thumbnails), the one of [AWS](https://docs.aws.amazon.com/mediapackage/latest/userguide/using-image-media-playlists.html) and the one of [Roku](https://developer.roku.com/en-gb/docs/developer-program/media-playback/trick-mode/hls-and-dash.md), for inspiration. Here is also an [extension](https://github.com/image-media-playlist/spec/blob/master/image_media_playlist_v0_4.pdf) to the RFC. We'll see later if we can/should do something in this area.
- Age rating is complex and we are probably a bit early since there is currently no support in our products. Some links [here](https://en.wikipedia.org/wiki/Motion_picture_content_rating_system) and [there](https://help.imdb.com/article/contribution/titles/certificates/GU757M8ZJ9ZPXB39?ref_=helpms_helpart_inline).
- Some schemas for inspiration:
    - https://schema.org/TVSeries
    - https://schema.org/TVEpisode
    - https://schema.org/video
    - https://schema.org/VideoObject
    - https://schema.org/MediaObject

## Developer meeting, December 4th

We had a look at the draft below again, which is likely sufficient to move on with #173.

## Final drafts

Note: We use a `?` to identify optional fields.

[Data Format](https://github.com/user-attachments/files/23928535/Player.Data.Format.json)

[Data Format (error)](https://github.com/user-attachments/files/23231491/player_data_forma_error.json)
