### ISSUE TITLE
API sync QoS

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-documentation#88]
- We discussed that `asset` and `metadata` timings we send represent the QoE timings (can be 0 for perfect preloading). But what about `drm` and `token` timings? Are QoE values meaningful? If not (and if we are really interested in such values) shouldn't we group QoS values and QoE values separately in our JSON?
- `total` for QoE global timing is probably misleading (suggests a sum, which might not be always the case). Can we find a better name?
- Should we group stall metrics into a `stall` JSON object?
- Shouldn't we rename `buffer_duration` as `buffer`, `available_buffer` or `buffer_health` (YouTube name)? (@jboix) 
- Maybe we need to introduce 3 types of timings for resource loading, see hints in the [following issue](https://github.com/SRGSSR/pillarbox-apple/issues/925).
- How could we manage versioning if the spec is changed?
-  Do we require events to be received sequentially? (e.g. START before STOP)

**Comment by amtins** [comment]
> We discussed that asset and metadata timings we send represent the QoE timings (can be 0 for perfect preloading). But what about drm and token timings? Are QoE values meaningful? If not (and if we are really interested in such values) shouldn't we group QoS values and QoE values separately in our JSON?

This is something that @bgaudaen wanted to have. From my point of view if it's easy to send why not, if it requires a ridiculous amount of work to send I would be more than incline not to. 

> total for QoE global timing is probably misleading (suggests a sum, which might not be always the case). Can we find a better name?

In which case this is not the case?

> Shouldn't we rename buffer_duration as buffer, available_buffer or buffer_health

What this field represents ? The buffer's duration so `buffer_duration` is self explanatory. `buffer_health` doesn't meaning anything, what kind of value is expected ? `buffer_health: "is good"`, `buffer_health: "is meh"`, `buffer_health: "feels a bit sick"`, so a strong no for me. `available_buffer` in terms of semantic starting by a noun is better.

> Should we group stall metrics into a stall JSON object?

According to the comment [issuecomment-2165008531](https://github.com/SRGSSR/pillarbox-documentation/issues/70#issuecomment-2165008531) it's already the case. Maybe I'm missing something? My current implementation follows this guideline. To be honest I would prefer sending the stall as an event, this would avoid keeping track of this information during the playback session and would find easier to process on a backend. Lets simulate a session with the id XYZ:

```
START:XYZ:....
HEARTBEAT:XYZ:....
HEARTBEAT:XYZ:....
HEARTBEAT:XYZ:....
STALL:XYZ:420 // 420 is the duration in MS
HEARTBEAT:XYZ:....
STALL:XYZ:3569
... // etc
```
If I want to select the sum of the stall duration from all the events on earth where the event name is stall and the session id is XYZ, it would be easy. In other words: `SELECT SUM(duration) AS stall_duration FROM all_the_events_on_earth WHERE event = 'stall' AND session_id = 'XYZ'`

<img src="https://media1.tenor.com/m/klvZRKP7BL4AAAAd/mr-bean-thank-you.gif" alt="purfect" width="150"/>

That said I'm fine with the stall object.

**Comment by defagos** [comment]
> This is something that @bgaudaen wanted to have. From my point of view if it's easy to send why not, if it requires a ridiculous amount of work to send I would be more than incline not to.

On Apple platforms finding how much time is required to load a resource once its URL is known is simply not possible in all cases. If preloading is involved we measure a time of 0, we cannot know how much time was actually required for the whole preloading process.

> In which case this is not the case?

Depending on how things are measured some overhead (e.g. time required to run code locally) might be missing. But I agree with you most of the time we should be able to measure things in a way that this is the case.

> What this field represents ? 

As suggested by @jboix `buffer_duration` might be interpreted as _the time during which the player is buffering_, thus the idea of a more expressive name.

> According to the comment https://github.com/SRGSSR/pillarbox-documentation/issues/70#issuecomment-2165008531 it's already the case.

You're right, not sure where I read about the old format.

> To be honest I would prefer sending the stall as an event

Possible but I guess we would need two events. When the player stalls you don't know how much time it stalls. Maybe it will stall and then crash. So you probably need a stall and a resume from stall events, with the difference between consecutive event pairs telling you the duration of that particular stall.

**Comment by defagos** [comment]
# But what about drm and token timings? 

# `total` for QoE global timing is probably misleading (suggests a sum, which might not be always the case). Can we find a better name?

# Should we group stall metrics into a stall JSON object?

# Shouldn't we rename buffer_duration as buffer, available_buffer or buffer_health (YouTube name)? (@jboix)

# Maybe we need to introduce 3 types of timings for resource loading, see hints in the https://github.com/SRGSSR/pillarbox-apple/issues/925.

# How could we manage versioning if the spec is changed?

# Do we require events to be received sequentially? (e.g. START before STOP)
